### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by jasoncookecon** [michaelpollmann/spatialTreat-example#1]
I noticed the Readme mentioned the following files 04_pick_counterfactuals.R, 05_estimate_effects.R. But they do not appear in the code repository. Are you planning on including these?

**Comment by michaelpollmann** [comment]
code for picking counterfactual locations from the neural network output and estimating effects and standard errors has been added with commits 19b1c6af4c923a660ea2ecf9056b298903b8d40f and 6f2edfa00894f60ad7dc10369e6b253d8d2eebe0
